/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-05-08 04:45:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.User;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <title>Thông tin cá nhân</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Font: Source Sans Pro -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\r\n");
      out.write("  <!-- Font Awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("  <!-- Theme style -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"dist/css/adminlte.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition sidebar-mini\">\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <!-- Navbar -->\r\n");
      out.write("    <nav class=\"main-header navbar navbar-expand navbar-white navbar-light\">\r\n");
      out.write("      <!-- Left navbar links -->\r\n");
      out.write("      <ul class=\"navbar-nav\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" data-widget=\"pushmenu\" href=\"#\" role=\"button\"><i class=\"fas fa-bars\"></i></a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("          <a href=\"index3.html\" class=\"nav-link\">Thông tin cá nhân</a>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <!-- Right navbar links -->\r\n");
      out.write("      <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <nav class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("              <span class=\"navbar-brand\">UserName</span>\r\n");
      out.write("              <a class=\"btn navbar-btn btn-primary navbar-right\" role=\"button\" href=\"#\">Đăng xuất</a>\r\n");
      out.write("          </nav>\r\n");
      out.write("          \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"dropdown\" style=\"display: inline-block;\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink78\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Ngôn ngữ</a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink78\"> \r\n");
      out.write("            <a class=\"dropdown-item\" href=\"#\"><span class=\"flag-icon flag-icon-us\"></span> English</a> \r\n");
      out.write("            <a class=\"dropdown-item\" href=\"#\"><span class=\"flag-icon flag-icon-fr\"></span> Tiếng Việt</a> \r\n");
      out.write("            <a class=\"dropdown-item\" href=\"#\"><span class=\"flag-icon flag-icon-de\"></span> Japan</a> \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- /.navbar -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Main Sidebar Container -->\r\n");
      out.write("  <aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\r\n");
      out.write("    <!-- Brand Logo -->\r\n");
      out.write("    <a href=\"../../index3.html\" class=\"brand-link\">\r\n");
      out.write("      <img src=\"dist/img/AdminLTELogo.png\" alt=\"AdminLTE Logo\" class=\"brand-image img-circle elevation-3\" style=\"opacity: .8\">\r\n");
      out.write("      <span class=\"brand-text font-weight-light\">AdminLTE 3</span>\r\n");
      out.write("    </a>\r\n");
      out.write("  <!-- Sidebar Menu -->\r\n");
      out.write("  <nav class=\"mt-2\">\r\n");
      out.write("    <ul class=\"nav nav-pills nav-sidebar flex-column\" data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\r\n");
      out.write("      <!-- Add icons to the links using the .nav-icon class\r\n");
      out.write("         with font-awesome or any other icon font library -->\r\n");
      out.write("      <li class=\"nav-item menu-open\">\r\n");
      out.write("        <a href=\"./index.html\" class=\"nav-link active\">\r\n");
      out.write("          <i class=\"nav-icon fas fa-home\"></i>\r\n");
      out.write("          <p>\r\n");
      out.write("           Trang chủ\r\n");
      out.write("          </p>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item menu-open\">\r\n");
      out.write("        <a href=\"\" class=\"nav-link \">\r\n");
      out.write("          <i class=\"nav-icon fas fa-cart-arrow-down\"></i>\r\n");
      out.write("          <p>\r\n");
      out.write("            Bán hàng\r\n");
      out.write("          </p>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item menu-open\">\r\n");
      out.write("        <a href=\"pages/tables/product.html\" class=\"nav-link \">\r\n");
      out.write("          <i class=\"nav-icon fas fa-list-alt\"></i>\r\n");
      out.write("          <p>\r\n");
      out.write("            Quản lý sản phẩm\r\n");
      out.write("          </p>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("          <i class=\"nav-icon fas fa-cubes\"></i>\r\n");
      out.write("          <p>\r\n");
      out.write("            Quản lý kho\r\n");
      out.write("            <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("          </p>\r\n");
      out.write("        </a>\r\n");
      out.write("        <ul class=\"nav nav-treeview\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"\" class=\"nav-link\">\r\n");
      out.write("              <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("              <p>Xem kho hàng</p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"\" class=\"nav-link\">\r\n");
      out.write("              <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("              <p>Nhập kho</p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"\" class=\"nav-link\">\r\n");
      out.write("              <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("              <p>Xuất kho</p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("     \r\n");
      out.write("      <li class=\"nav-item menu-open\">\r\n");
      out.write("        <a href=\"./index.html\" class=\"nav-link \">\r\n");
      out.write("          <i class=\"nav-icon fas fa-address-book\"></i>\r\n");
      out.write("          <p>\r\n");
      out.write("            Quản lý nhà cung cấp\r\n");
      out.write("          </p>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("     \r\n");
      out.write("      <li class=\"nav-item menu-open\">\r\n");
      out.write("        <a href=\"pages/tables/staff.html\" class=\"nav-link \">\r\n");
      out.write("          <i class=\"nav-icon fas  fa-address-card\"></i>\r\n");
      out.write("          <p>\r\n");
      out.write("            Quản lý nhân viên\r\n");
      out.write("          </p>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item menu-open\">\r\n");
      out.write("        <a href=\"./index.html\" class=\"nav-link \">\r\n");
      out.write("          <i class=\"nav-icon fas fa-file-invoice\"></i>\r\n");
      out.write("          <p>\r\n");
      out.write("            Quản lý hóa đơn\r\n");
      out.write("          </p>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("          <i class=\"nav-icon fas fa-chart-pie\"></i>\r\n");
      out.write("          <p>\r\n");
      out.write("            Thống kê\r\n");
      out.write("            <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("          </p>\r\n");
      out.write("        </a>\r\n");
      out.write("        <ul class=\"nav nav-treeview\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"\" class=\"nav-link\">\r\n");
      out.write("              <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("              <p>Doanh thu</p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"\" class=\"nav-link\">\r\n");
      out.write("              <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("              <p>Hàng tồn kho</p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item menu-open\">\r\n");
      out.write("        <a href=\"./index.html\" class=\"nav-link \">\r\n");
      out.write("          <i class=\"nav-icon fas fa-file-export\"></i>\r\n");
      out.write("          <p>\r\n");
      out.write("            Báo cáo\r\n");
      out.write("          </p>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- /.sidebar-menu -->\r\n");
      out.write("  </aside>\r\n");
      out.write("\r\n");
      out.write("  <!-- Content Wrapper. Contains page content -->\r\n");
      out.write("  <div class=\"content-wrapper\">\r\n");
      out.write("    <!-- Content Header (Page header) -->\r\n");
      out.write("    <section class=\"content-header\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row mb-2\">\r\n");
      out.write("          <div class=\"col-sm-6\">\r\n");
      out.write("           \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm-6\">\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div><!-- /.container-fluid -->\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main content -->\r\n");
      out.write("    <section class=\"content\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("           ");
User user = (User) session.getAttribute("user") ;
             String name  = user.getName();
           
      out.write("\r\n");
      out.write("            <!-- Profile Image -->\r\n");
      out.write("            <div class=\"card card-primary card-outline\">\r\n");
      out.write("              <div class=\"card-body box-profile\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                  <img class=\"profile-user-img img-fluid img-circle\"\r\n");
      out.write("                       src=\"dist/img/user4-128x128.jpg\"\r\n");
      out.write("                       alt=\"User profile picture\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <h3 class=\"profile-username text-center\">");
      out.print( name);
      out.write("</h3>\r\n");
      out.write("                <ul class=\"list-group list-group-unbordered mb-3\">\r\n");
      out.write("                  <li class=\"list-group-item\">\r\n");
      out.write("                    <b>Ngày sinh</b> <a class=\"float-right\">");
      out.print(user.getBirthDay() );
      out.write("</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                \r\n");
      out.write("                  <li class=\"list-group-item\">\r\n");
      out.write("                    <b>Số điện thoại</b> <a class=\"float-right\">");
      out.print( user.getPhoneNumber() );
      out.write("</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("              \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.card-body -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.card -->\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.col -->\r\n");
      out.write("          <div class=\"col-md-9\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <div class=\"card-header p-2\">\r\n");
      out.write("                <ul class=\"nav nav-pills\">\r\n");
      out.write("                   <li class=\"nav-item\"><a class=\"nav-link active\" href=\"#settings\" data-toggle=\"tab\">Thông tin</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"><a class=\"nav-link \" href=\"#activity\" data-toggle=\"tab\">Đổi mật khẩu</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"><a class=\"nav-link\" href=\"#timeline\" data-toggle=\"tab\">Lịch sử làm việc</a></li>\r\n");
      out.write("               \r\n");
      out.write("                </ul>\r\n");
      out.write("              </div><!-- /.card-header -->\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"tab-content\">\r\n");
      out.write("                  <div class=\" tab-pane\" id=\"activity\">\r\n");
      out.write("                    <div class=\"card-body col-md-12 \">\r\n");
      out.write("                  \r\n");
      out.write("                      <form action=\"\" method=\"post\" >\r\n");
      out.write("                        <div class=\"input-group mb-3 \">\r\n");
      out.write("                          <input type=\"password\" class=\"form-control\" placeholder=\"Mật khẩu hiện tại\">\r\n");
      out.write("                          <div class=\"input-group-append\">\r\n");
      out.write("                            <div class=\"input-group-text\">\r\n");
      out.write("                              <span class=\"fas fa-lock\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"input-group mb-3\">\r\n");
      out.write("                          <input type=\"password\" class=\"form-control\" placeholder=\"Mật khẩu mới\">\r\n");
      out.write("                          <div class=\"input-group-append\">\r\n");
      out.write("                            <div class=\"input-group-text\">\r\n");
      out.write("                              <span class=\"fas fa-lock\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"input-group mb-3\">\r\n");
      out.write("                          <input type=\"password\" class=\"form-control\" placeholder=\"Xác nhận mật khẩu mới\">\r\n");
      out.write("                          <div class=\"input-group-append\">\r\n");
      out.write("                            <div class=\"input-group-text\">\r\n");
      out.write("                              <span class=\"fas fa-lock\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row  d-flex justify-content-center\">\r\n");
      out.write("                          <div class=\"\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary btn-block\">Cập nhật</button>\r\n");
      out.write("                          </div>\r\n");
      out.write("                     \r\n");
      out.write("                        </div>\r\n");
      out.write("                      </form>\r\n");
      out.write("              \r\n");
      out.write("                    </div>\r\n");
      out.write("               \r\n");
      out.write("                    \r\n");
      out.write("                  </div>\r\n");
      out.write("              \r\n");
      out.write("\r\n");
      out.write("                  <div class=\"active tab-pane\" id=\"settings\">\r\n");
      out.write("                    <form class=\"form-horizontal\">\r\n");
      out.write("                      <div class=\"form-group row\">\r\n");
      out.write("                        <label  class=\"col-sm-2 col-form-label\">Tên</label>\r\n");
      out.write("                        <div class=\"col-sm-10\">\r\n");
      out.write("                      \r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"name\"  placeholder=\"Tên\"  value=");
      out.print( user.getName() );
      out.write(" >\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-group row\">\r\n");
      out.write("                        <label for=\"inputEmail\" class=\"col-sm-2 col-form-label\">Ngày sinh</label>\r\n");
      out.write("                        <div class=\"col-sm-10\">\r\n");
      out.write("                          <input type=\"date\" class=\"form-control\" id=\"date\"  value=");
      out.print( user.getBirthDay() );
      out.write(">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-group row\">\r\n");
      out.write("                        <label for=\"inputName2\" class=\"col-sm-2 col-form-label\">Số điện thoại</label>\r\n");
      out.write("                        <div class=\"col-sm-10\">\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"phone\" placeholder=\"Số điện thoại\"  value=");
      out.print( user.getPhoneNumber() );
      out.write(" >\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-group row\">\r\n");
      out.write("                        <label for=\"inputName2\" class=\"col-sm-2 col-form-label\">Ảnh</label>\r\n");
      out.write("                        <div class=\"col-sm-10\">\r\n");
      out.write("                          <input type=\"file\"  >\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      \r\n");
      out.write("                      \r\n");
      out.write("                      <div class=\"form-group row d-flex justify-content-center\">\r\n");
      out.write("                        <div class=\"\">\r\n");
      out.write("                          <button type=\"submit\" class=\"btn btn-primary\">Cập nhật</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- /.tab-pane -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.tab-content -->\r\n");
      out.write("              </div><!-- /.card-body -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.card -->\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.col -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row -->\r\n");
      out.write("      </div><!-- /.container-fluid -->\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- /.content -->\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Control Sidebar -->\r\n");
      out.write("  <aside class=\"control-sidebar control-sidebar-dark\">\r\n");
      out.write("    <!-- Control sidebar content goes here -->\r\n");
      out.write("  </aside>\r\n");
      out.write("  <!-- /.control-sidebar -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap 4 -->\r\n");
      out.write("<script src=\"plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- AdminLTE App -->\r\n");
      out.write("<script src=\"dist/js/adminlte.min.js\"></script>\r\n");
      out.write("<!-- AdminLTE for demo purposes -->\r\n");
      out.write("<script src=\"dist/js/demo.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
