/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-05-04 17:18:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import util.Util;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("util.Util");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <title>Đăng ký</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Font: Source Sans Pro -->\r\n");
      out.write("  <link rel=\"stylesheet\"\r\n");
      out.write("    href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\r\n");
      out.write("  <!-- Font Awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("  <!-- icheck bootstrap -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plugins/icheck-bootstrap/icheck-bootstrap.min.css\">\r\n");
      out.write("  <!-- Theme style -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"dist/css/adminlte.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"hold-transition register-page\">\r\n");
      out.write("  <div class=\"register-box\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card card-outline card-primary\">\r\n");
      out.write("      <div class=\"card-header text-center\">\r\n");
      out.write("        <a href=\"\" class=\"h1\"><b>Admin</b>LTE</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-body register-card-body\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <form onsubmit=\"return validateForm()\" action=\"OTPController\" method=\"post\" id=\"form-register\" >\r\n");
      out.write("          <div class=\"input-group mb-3\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control \" id=\"fullName\" name=\"fullName\" placeholder=\"Họ và tên\">\r\n");
      out.write("            <div class=\"invalid-feedback order-last err1\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input-group-append\">\r\n");
      out.write("              <div class=\"input-group-text\">\r\n");
      out.write("                <span class=\"fas fa-user\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-group mb-3\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control \" id=\"storeName\" name=\"storeName\" placeholder=\"Tên cửa hàng của bạn\">\r\n");
      out.write("            <div class=\"invalid-feedback order-last err2\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input-group-append\">\r\n");
      out.write("              <div class=\"input-group-text\">\r\n");
      out.write("                <span class=\"fas fa-store\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-group mb-3\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control \" id=\"dayofbirth\" name=\"dayOfBirth\" placeholder=\"Ngày sinh\"\r\n");
      out.write("              onfocus=\"(this.type='date')\">\r\n");
      out.write("            <div class=\"invalid-feedback order-last err3\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input-group-append\">\r\n");
      out.write("              <div class=\"input-group-text\">\r\n");
      out.write("\r\n");
      out.write("                <span class=\"fas fa-birthday-cake\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-group mb-3\">\r\n");
      out.write("            <input type=\"email\" class=\"form-control \" id=\"email\" name=\"userName\" placeholder=\"Email\">\r\n");
      out.write("            <div class=\"invalid-feedback order-last err4\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input-group-append\">\r\n");
      out.write("              <div class=\"input-group-text\">\r\n");
      out.write("                <span class=\"fas fa-envelope\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-group mb-3\">\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" placeholder=\"Mật khẩu\" minlength=\"6\">\r\n");
      out.write("            <div class=\"invalid-feedback order-last err5\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input-group-append\">\r\n");
      out.write("              <div class=\"input-group-text\">\r\n");
      out.write("                <span class=\"fas fa-lock\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-group mb-3\">\r\n");
      out.write("            <input type=\"password\" class=\"form-control \" id=\"repassword\" name=\"repassword\"\r\n");
      out.write("              placeholder=\"Nhập lại mật khẩu\" minlength=\"6\">\r\n");
      out.write("            <div class=\"invalid-feedback order-last err6\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input-group-append\">\r\n");
      out.write("              <div class=\"input-group-text\">\r\n");
      out.write("                <span class=\"fas fa-lock\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("      \r\n");
      out.write("          <br>\r\n");
      out.write("          <div class=\"col-6 justify-content-center mx-auto text-center\">\r\n");
      out.write("\r\n");
      out.write("            <input type=\"submit\" class=\"btn btn-block btn-primary\" value=\"Đăng ký\">\r\n");
      out.write("                 \r\n");
      out.write("            </input>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <p style=\"text-align: center;\">Nếu bạn có tài khoản vui lòng? <a href=\"\" class=\"text-center text-danger\">Đăng\r\n");
      out.write("            nhập</a></p>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /.form-box -->\r\n");
      out.write("    </div><!-- /.card -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.register-box -->\r\n");
      out.write("\r\n");
      out.write("  <!-- jQuery -->\r\n");
      out.write("  <script src=\"plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <!-- Bootstrap 4 -->\r\n");
      out.write("  <script src=\"plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <!-- AdminLTE App -->\r\n");
      out.write("  <script src=\"dist/js/adminlte.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    var existEmail = false;\r\n");
      out.write("    function validateForm() {\r\n");
      out.write("      var countError = 0;\r\n");
      out.write("      var fullName = $('#fullName').val();\r\n");
      out.write("      var storeName = $('#storeName').val();\r\n");
      out.write("      var date = $('#dayofbirth').val();\r\n");
      out.write("      var email = $('#email').val();\r\n");
      out.write("      var pass = $('#password').val();\r\n");
      out.write("      var repass = $('#repassword').val();\r\n");
      out.write("      var otp = $('#otpcode').val();\r\n");
      out.write(" \r\n");
      out.write("      if (fullName.length == 0) {\r\n");
      out.write("        countError++;\r\n");
      out.write("        showError('#fullName', 'err1', 'Vui lòng nhập họ và tên!');\r\n");
      out.write("\r\n");
      out.write("      } else removeError('#fullName');\r\n");
      out.write("\r\n");
      out.write("      if (storeName.length == 0) {\r\n");
      out.write("        countError++;\r\n");
      out.write("        showError('#storeName', 'err2', 'Vui lòng nhập tên cửa hàng!')\r\n");
      out.write("\r\n");
      out.write("      } else removeError('#storeName');\r\n");
      out.write("      if (date.length == 0) {\r\n");
      out.write("        countError++;\r\n");
      out.write("        showError('#dayofbirth', 'err3', 'Vui lòng nhập ngày sinh!')\r\n");
      out.write("\r\n");
      out.write("      } else removeError('#dayofbirth');\r\n");
      out.write("      if (email.length == 0) {\r\n");
      out.write("        countError++;\r\n");
      out.write("        showError('#email', 'err4', 'Vui lòng nhập email!')\r\n");
      out.write("\r\n");
      out.write("      } else  if(!validateEmail(email)) {\r\n");
      out.write("    \t  countError++;\r\n");
      out.write("          showError('#email', 'err4', 'Sai định dạng email!');\r\n");
      out.write("           \r\n");
      out.write("          }else {\r\n");
      out.write("        \t  if(!existEmail) {\r\n");
      out.write("        \t\t  removeError('#email');\r\n");
      out.write("        \t  }else {\r\n");
      out.write("        \t\t  countError++;\r\n");
      out.write("                  showError('#email', 'err4', 'Email đã tồn tại!');\r\n");
      out.write("        \t  }\r\n");
      out.write("        \t\r\n");
      out.write("          }\r\n");
      out.write("      \r\n");
      out.write(" \r\n");
      out.write("      if (pass.length == 0) {\r\n");
      out.write("        countError++;\r\n");
      out.write("        showError('#password', 'err5', 'Vui lòng nhập mật khẩu!')\r\n");
      out.write("\r\n");
      out.write("      } else {\r\n");
      out.write("        if (!checkCorrectPass(pass)) {\r\n");
      out.write("          countError++;\r\n");
      out.write("          showError('#password', 'err5', 'Mật khẩu tối thiểu 6 ký tự!')\r\n");
      out.write("\r\n");
      out.write("        } else {\r\n");
      out.write("          removeError('#password');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      if (repass.length == 0) {\r\n");
      out.write("        countError++;\r\n");
      out.write("        showError('#repassword', 'err6', 'Vui lòng nhập xác nhập mật khẩu!')\r\n");
      out.write("\r\n");
      out.write("      }else {\r\n");
      out.write("        if(checkSamePass(pass,repass)) {\r\n");
      out.write("         removeError('#repassword');\r\n");
      out.write("         \r\n");
      out.write("\r\n");
      out.write("        }else {\r\n");
      out.write("          countError++;\r\n");
      out.write("          showError('#repassword', 'err6', 'Mật khẩu không khớp!')\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write(" \r\n");
      out.write("      console.log(countError);\r\n");
      out.write("      if (countError == 0) {\r\n");
      out.write("    \t \r\n");
      out.write("        return true;\r\n");
      out.write("      }else {\r\n");
      out.write("    \t   return false;  \r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("function checkCorrectPass(pass) {\r\n");
      out.write("  return (pass.length > 5) ? true : false;\r\n");
      out.write("}\r\n");
      out.write("    function showError(element, element2, mes) {\r\n");
      out.write("      $(element).addClass('is-invalid');\r\n");
      out.write("      $('.' + element2).text(mes);\r\n");
      out.write("    }\r\n");
      out.write("    function removeError(element) {\r\n");
      out.write("      $(element).removeClass('is-invalid');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function checkSamePass(pass,repass) {\r\n");
      out.write("      return (pass == repass) ? true: false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("\r\n");
      out.write("      // fulName\r\n");
      out.write("      $('#fullName').on('keyup', function () {\r\n");
      out.write("\r\n");
      out.write("        if ($('#fullName').val().length > 0) {\r\n");
      out.write("          $('#fullName').removeClass('is-invalid');\r\n");
      out.write("        } else {\r\n");
      out.write("          $('#fullName').addClass('is-invalid');\r\n");
      out.write("        }\r\n");
      out.write("      })\r\n");
      out.write("\r\n");
      out.write("      // email \r\n");
      out.write("      $('#email').on('keyup',function() {\r\n");
      out.write("         var email = $('#email').val();\r\n");
      out.write("         if(email.length >0) {\r\n");
      out.write("             $.ajax ({\r\n");
      out.write("                 type: 'POST',\r\n");
      out.write("                 dataType :'html',\r\n");
      out.write("                 data : {\r\n");
      out.write("                     userName : email,\r\n");
      out.write("                 },\r\n");
      out.write("                 url :'AjaxUser',\r\n");
      out.write("                 success: function(result) {\r\n");
      out.write("                   if(result =='valid') {\r\n");
      out.write("                \t   removeError('#email');\r\n");
      out.write("                \t   $('#email').addClass('is-valid');\r\n");
      out.write("                \t   existEmail = false;\r\n");
      out.write("                \t   \r\n");
      out.write("                   }else {\r\n");
      out.write("                     if(result =='invalid') {\r\n");
      out.write("                    \t  showError('#email', 'err4', 'Email đã tồn tại!');\r\n");
      out.write("                    \t  existEmail = true;\r\n");
      out.write("                    \t  \r\n");
      out.write("                     }\r\n");
      out.write("                   }\r\n");
      out.write("                 }\r\n");
      out.write("\r\n");
      out.write("             })\r\n");
      out.write("\r\n");
      out.write("         }else {\r\n");
      out.write("           showError('#email','err4','Vui lòng nhập email!');\r\n");
      out.write("         }\r\n");
      out.write("      })\r\n");
      out.write("\r\n");
      out.write("      // storeName\r\n");
      out.write("      $('#storeName').on('keyup', function () {\r\n");
      out.write("\r\n");
      out.write("        if ($('#storeName').val().length > 0) {\r\n");
      out.write("          $('#storeName').removeClass('is-invalid');\r\n");
      out.write("        } else {\r\n");
      out.write("          $('#storeName').addClass('is-invalid');\r\n");
      out.write("        }\r\n");
      out.write("      })\r\n");
      out.write("      // validate date\r\n");
      out.write("      $('#dayofbirth').change(function () {\r\n");
      out.write("        $('#dayofbirth').removeClass('is-invalid');\r\n");
      out.write("      })\r\n");
      out.write("      //  validate onkey up\r\n");
      out.write("      $('#password, #repassword').on('keyup', function () {\r\n");
      out.write("        //pass\r\n");
      out.write("\r\n");
      out.write("        if ($('#password').val().length < 6) {\r\n");
      out.write("          showError('#password', 'err5', 'Mật khẩu tối thiểu 6 ký tự!');\r\n");
      out.write("          showError('#repassword', 'err6', 'Mật khẩu không khớp!');\r\n");
      out.write("        } else {\r\n");
      out.write("          $('#password').removeClass('is-invalid');\r\n");
      out.write("          $('#password').addClass('is-valid');\r\n");
      out.write("\r\n");
      out.write("          if ( checkSamePass( $('#password').val(),$('#repassword').val())) {\r\n");
      out.write("\r\n");
      out.write("            $('#repassword').removeClass('is-invalid');\r\n");
      out.write("            $('#repassword').addClass('is-valid');\r\n");
      out.write("          } else {\r\n");
      out.write("            showError('#repassword', 'err6', 'Mật khẩu không khớp!');\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("      })\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    function validateEmail(email) {\r\n");
      out.write(" \t\t var emailReg = /^([\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4})?$/;\r\n");
      out.write("  \t\t\treturn emailReg.test(email);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
